---
-   hosts: govproxy-nodes
    vars_files:
        - git-vars.yml
    gather_facts: true
    become: true

    tasks:
        - name: Pull sources from the repository.
          git: repo={{project_repo}} dest={{project_root}} version={{branch}} force={{force}}
          notify:
            - sync local files
            - restart squid

    handlers:
      - import_tasks: git-handler.yml

