- hosts: govproxy-nodes
  tasks:
    - name:  add entry to hosts
      shell: echo '$IP   global.catalog' >> /etc/hosts
      args:
         chdir: /etc/
         executable: /bin/bash

    - name:  restart SQUID
      shell: systemctl reload squid.service
      args:
         chdir: /etc/
         executable: /bin/bash

